package httpadapter

import (
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	"github.com/labstack/echo/v4"

	"github.com/velopulent/cms/apps/backend-go/internal/application"
	"github.com/velopulent/cms/apps/backend-go/internal/domain"
	"github.com/velopulent/cms/apps/backend-go/internal/middleware"
	"github.com/velopulent/cms/apps/backend-go/internal/ports"
)

type RESTHandler struct{ services *application.Services }
func NewRESTHandler(s *application.Services) RESTHandler { return RESTHandler{s} }

func ptr[T any](v T) *T { return &v }

func (h RESTHandler) listSites(c echo.Context) error { if err:=middleware.RequireAdminScope(c,h.services,nil,application.ScopeSitesRead); err!=nil{return err}; v,err:=h.services.Sites.ListForPrincipal(c.Request().Context(),middleware.GetPrincipal(c)); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v) }
func (h RESTHandler) createSite(c echo.Context) error { if err:=middleware.RequireAdminScope(c,h.services,nil,application.ScopeSitesWrite);err!=nil{return err}; var req struct{Name string `json:"name"`; StorageProvider string `json:"storage_provider"`}; if err:=c.Bind(&req);err!=nil{return c.JSON(400,errorBody{"Invalid input"})}; p:=middleware.GetPrincipal(c); by:=p.UserID;if by==""{by="system"}; v,err:=h.services.Sites.Create(c.Request().Context(),req.Name,req.StorageProvider,by); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) getSite(c echo.Context) error { id:=c.Param("site_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeSitesRead);err!=nil{return err}; v,err:=h.services.Sites.Get(c.Request().Context(),id); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"Site not found"})}; return c.JSON(200,v)}
func (h RESTHandler) updateSite(c echo.Context) error { id:=c.Param("site_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeSitesWrite);err!=nil{return err}; var req struct{Name *string `json:"name"`}; _=c.Bind(&req); v,err:=h.services.Sites.Update(c.Request().Context(),id,req.Name); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) deleteSite(c echo.Context) error { id:=c.Param("site_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeSitesDelete);err!=nil{return err}; _,err:=h.services.Sites.Delete(c.Request().Context(),id); if err!=nil{return writeAnyError(c,err,500,"")}; return c.NoContent(204)}
func (h RESTHandler) listMembers(c echo.Context) error { id:=c.Param("site_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeMembersRead);err!=nil{return err}; v,err:=h.services.Sites.ListMembers(c.Request().Context(),id); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) inviteMember(c echo.Context) error { id:=c.Param("site_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeMembersWrite);err!=nil{return err}; var req struct{Username string `json:"username"`; Role string `json:"role"`}; _=c.Bind(&req); v,err:=h.services.Sites.InviteMember(c.Request().Context(),id,req.Username,req.Role); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) updateMember(c echo.Context) error { id:=c.Param("site_id"); uid:=c.Param("user_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeMembersWrite);err!=nil{return err}; var req struct{Role string `json:"role"`}; _=c.Bind(&req); v,err:=h.services.Sites.UpdateMemberRole(c.Request().Context(),id,uid,req.Role); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"Member not found"})}; return c.JSON(200,v)}
func (h RESTHandler) removeMember(c echo.Context) error { id:=c.Param("site_id"); uid:=c.Param("user_id"); if err:=middleware.RequireAdminScope(c,h.services,&id,application.ScopeMembersWrite);err!=nil{return err}; by:=middleware.GetPrincipal(c).UserID; n,err:=h.services.Sites.RemoveMember(c.Request().Context(),id,uid,by); if err!=nil{return writeAnyError(c,err,500,"")}; if n==0{return c.JSON(404,errorBody{"Member not found"})}; return c.NoContent(204)}

func (h RESTHandler) siteFor(c echo.Context, scope, role string)(string,error){return middleware.ResolveSite(c,h.services,scope,role)}
func (h RESTHandler) listCollections(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Collections.List(c.Request().Context(),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) getCollection(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Collections.Get(c.Request().Context(),site,c.Param("collection_slug")); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"Collection not found"})}; return c.JSON(200,v)}
func (h RESTHandler) createCollection(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaWrite,"editor"); if err!=nil{return err}; var req struct{Name string `json:"name"`; Slug string `json:"slug"`; Definition any `json:"definition"`; IsSingleton *bool `json:"is_singleton"`}; _=c.Bind(&req); singleton:=false;if req.IsSingleton!=nil{singleton=*req.IsSingleton}; v,err:=h.services.Collections.Create(c.Request().Context(),site,req.Name,req.Slug,req.Definition,singleton); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) updateCollection(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaWrite,"editor"); if err!=nil{return err}; var req struct{Name *string `json:"name"`; Slug *string `json:"slug"`; Definition any `json:"definition"`}; _=c.Bind(&req); v,err:=h.services.Collections.Update(c.Request().Context(),site,c.Param("collection_slug"),req.Name,req.Slug,req.Definition); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) deleteCollection(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaWrite,"editor"); if err!=nil{return err}; _,err=h.services.Collections.Delete(c.Request().Context(),site,c.Param("collection_slug")); if err!=nil{return writeAnyError(c,err,500,"")}; return c.NoContent(204)}
func (h RESTHandler) listSingletons(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Collections.ListSingletons(c.Request().Context(),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) getSingleton(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Collections.GetSingleton(c.Request().Context(),site,c.Param("slug")); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) updateSingleton(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeSchemaWrite,"editor"); if err!=nil{return err}; var req struct{Data any `json:"data"`}; _=c.Bind(&req); v,err:=h.services.Collections.UpdateSingleton(c.Request().Context(),site,c.Param("slug"),req.Data); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}

func page(c echo.Context, def, max int64) int64 { v,_:=strconv.ParseInt(c.QueryParam("page"),10,64); if v<1{v=def}; if max>0&&v>max{v=max}; return v }
func (h RESTHandler) listEntries(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentRead,"viewer"); if err!=nil{return err}; p:=middleware.GetPrincipal(c); published:=p.Kind==ports.PrincipalSite; status:=c.QueryParam("status"); if p.Kind!=ports.PrincipalUser{status=""}; v,err:=h.services.Entries.List(c.Request().Context(),ports.ListEntriesParams{SiteID:site,CollectionSlug:c.QueryParam("type"),Status:status,Search:c.QueryParam("search"),PublishedOnly:published,Page:page(c,1,0),PerPage:pageVal(c,"per_page",50,200)}); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func pageVal(c echo.Context,k string,def,max int64)int64{v,_:=strconv.ParseInt(c.QueryParam(k),10,64); if v<1{v=def}; if max>0&&v>max{v=max}; return v}
func (h RESTHandler) getEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Entries.Get(c.Request().Context(),c.Param("id"),site,middleware.GetPrincipal(c).Kind==ports.PrincipalSite); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"Entry not found"})}; return c.JSON(200,v)}
func (h RESTHandler) createEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; var req struct{CollectionID string `json:"collection_id"`; Data any `json:"data"`; Slug string `json:"slug"`}; _=c.Bind(&req); by:=userPtr(c); v,err:=h.services.Entries.Create(c.Request().Context(),site,req.CollectionID,req.Data,req.Slug,by); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func userPtr(c echo.Context)*string{u:=middleware.GetPrincipal(c).UserID;if u==""{return nil};return &u}
func (h RESTHandler) updateEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; var req struct{Data any `json:"data"`; Slug *string `json:"slug"`; Status *string `json:"status"`; ChangeSummary *string `json:"change_summary"`}; _=c.Bind(&req); v,err:=h.services.Entries.Update(c.Request().Context(),c.Param("id"),site,req.Data,req.Slug,req.Status,userPtr(c),req.ChangeSummary); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) deleteEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; _,err=h.services.Entries.Delete(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.NoContent(204)}
func (h RESTHandler) publishEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; v,err:=h.services.Entries.Publish(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) unpublishEntry(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; v,err:=h.services.Entries.Unpublish(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) listRevisions(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Entries.ListRevisions(c.Request().Context(),c.Param("id"),site,page(c,1,0),pageVal(c,"per_page",50,200)); if err!=nil{return writeAnyError(c,err,500,"")}; items:=[]domain.EntryRevisionResponse{}; for _,r:=range v.Items{items=append(items,application.RevisionResponse(r))}; return c.JSON(200,map[string]any{"items":items,"total":v.Total,"page":v.Page,"per_page":v.PerPage})}
func (h RESTHandler) getRevision(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentRead,"viewer"); if err!=nil{return err}; n,_:=strconv.ParseInt(c.Param("number"),10,64); v,err:=h.services.Entries.GetRevision(c.Request().Context(),c.Param("id"),site,n); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"Revision not found"})}; return c.JSON(200,application.RevisionResponse(*v))}
func (h RESTHandler) restoreRevision(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeContentWrite,"editor"); if err!=nil{return err}; n,_:=strconv.ParseInt(c.Param("number"),10,64); v,err:=h.services.Entries.RestoreRevision(c.Request().Context(),c.Param("id"),site,n,userPtr(c)); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}

func (h RESTHandler) listFiles(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsRead,"viewer"); if err!=nil{return err}; trashed:=c.QueryParam("trashed")=="true"; v,err:=h.services.Files.List(c.Request().Context(),ports.ListFilesParams{SiteID:site,Trashed:trashed,Search:c.QueryParam("search"),FileType:c.QueryParam("type"),Page:page(c,1,0),PerPage:30}); if err!=nil{return writeAnyError(c,err,500,"")}; items:=[]domain.FileWithURL{}; for _,f:=range v.Items{items=append(items,h.services.Files.WithURL(f))}; return c.JSON(200,map[string]any{"items":items,"total":v.Total,"page":v.Page,"per_page":v.PerPage})}
func (h RESTHandler) uploadFile(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; fh,err:=c.FormFile("file"); if err!=nil{return c.JSON(400,errorBody{"No file provided"})}; f,_:=fh.Open(); defer f.Close(); b,_:=io.ReadAll(f); ctype:=fh.Header.Get("Content-Type"); if ctype==""{ctype="application/octet-stream"}; v,err:=h.services.Files.Upload(c.Request().Context(),site,b,fh.Filename,ctype,userPtr(c)); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) getFile(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Files.Get(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; if v==nil{return c.JSON(404,errorBody{"File not found"})}; return c.JSON(200,h.services.Files.WithURL(*v))}
func (h RESTHandler) deleteFile(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; n,err:=h.services.Files.SoftDelete(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; if n==0{return c.JSON(404,errorBody{"File not found"})}; return c.JSON(200,map[string]string{"message":"File deleted"})}
func (h RESTHandler) restoreFile(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; n,err:=h.services.Files.Restore(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; if n==0{return c.JSON(404,errorBody{"File not found or not deleted"})}; return c.JSON(200,map[string]string{"message":"File restored"})}
func idsReq(c echo.Context)([]string,error){var req struct{IDs []string `json:"ids"`};err:=json.NewDecoder(c.Request().Body).Decode(&req);return req.IDs,err}
func (h RESTHandler) batchDelete(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; ids,_:=idsReq(c); if len(ids)==0{return c.JSON(400,errorBody{"No file IDs provided"})}; n,err:=h.services.Files.BatchSoftDelete(c.Request().Context(),site,ids); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,map[string]int64{"deleted":n})}
func (h RESTHandler) batchRestore(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; ids,_:=idsReq(c); if len(ids)==0{return c.JSON(400,errorBody{"No file IDs provided"})}; n,err:=h.services.Files.BatchRestore(c.Request().Context(),site,ids); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,map[string]int64{"restored":n})}
func (h RESTHandler) batchPermanentDelete(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsWrite,"editor"); if err!=nil{return err}; ids,_:=idsReq(c); if len(ids)==0{return c.JSON(400,errorBody{"No file IDs provided"})}; n,err:=h.services.Files.BatchPermanentDelete(c.Request().Context(),site,ids); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,map[string]int64{"deleted":n})}
func (h RESTHandler) fileReferences(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeAssetsRead,"viewer"); if err!=nil{return err}; v,err:=h.services.Files.References(c.Request().Context(),c.Param("id"),site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) serveFile(c echo.Context) error { thumb:=c.Param("thumb")!=""; b,ct,name,err:=h.services.Files.Serve(c.Request().Context(),c.Param("id"),thumb); if err!=nil{return writeAnyError(c,err,500,"")}; c.Response().Header().Set("Content-Type",ct); if !thumb{c.Response().Header().Set("Content-Disposition",`inline; filename="`+name+`"`)}; return c.Blob(200,ct,b)}

func (h RESTHandler) listInstanceTokens(c echo.Context) error { if err:=middleware.RequireAdminScope(c,h.services,nil,application.ScopeTokensRead);err!=nil{return err}; v,err:=h.services.Tokens.List(c.Request().Context(),"instance",nil); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) createInstanceToken(c echo.Context) error { if err:=middleware.RequireAdminScope(c,h.services,nil,application.ScopeTokensWrite);err!=nil{return err}; var req struct{Name string `json:"name"`; Scopes []string `json:"scopes"`}; _=c.Bind(&req); v,err:=h.services.Tokens.Create(c.Request().Context(),"instance",nil,req.Name,req.Scopes,nil); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) deleteInstanceToken(c echo.Context) error { if err:=middleware.RequireAdminScope(c,h.services,nil,application.ScopeTokensWrite);err!=nil{return err}; n,err:=h.services.Tokens.Delete(c.Request().Context(),c.Param("token_id"),"instance",nil); if err!=nil{return writeAnyError(c,err,500,"")}; if n==0{return c.JSON(404,errorBody{"Token not found"})}; return c.NoContent(204)}
func (h RESTHandler) listSiteTokens(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeTokensRead,"admin"); if err!=nil{return err}; v,err:=h.services.Tokens.List(c.Request().Context(),"site",&site); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(200,v)}
func (h RESTHandler) createSiteToken(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeTokensWrite,"admin"); if err!=nil{return err}; var req struct{Name string `json:"name"`; Scopes []string `json:"scopes"`}; _=c.Bind(&req); by:=userPtr(c); v,err:=h.services.Tokens.Create(c.Request().Context(),"site",&site,req.Name,req.Scopes,by); if err!=nil{return writeAnyError(c,err,500,"")}; return c.JSON(201,v)}
func (h RESTHandler) deleteSiteToken(c echo.Context) error { site,err:=h.siteFor(c,application.ScopeTokensWrite,"admin"); if err!=nil{return err}; n,err:=h.services.Tokens.Delete(c.Request().Context(),c.Param("token_id"),"site",&site); if err!=nil{return writeAnyError(c,err,500,"")}; if n==0{return c.JSON(404,errorBody{"Token not found"})}; return c.NoContent(204)}
