/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminSitesRouteImport } from './routes/_admin/sites'
import { Route as AdminSitesIndexRouteImport } from './routes/_admin/sites/index'
import { Route as AdminSitesSiteIdRouteImport } from './routes/_admin/sites.$siteId'
import { Route as AdminSitesSiteIdIndexRouteImport } from './routes/_admin/sites.$siteId/index'
import { Route as AdminSitesSiteIdContentTypesRouteImport } from './routes/_admin/sites.$siteId/content-types'
import { Route as AdminSitesSiteIdContentTypeSlugRouteImport } from './routes/_admin/sites.$siteId/content.$typeSlug'
import { Route as AdminSitesSiteIdContentTypeSlugIndexRouteImport } from './routes/_admin/sites.$siteId/content.$typeSlug/index'
import { Route as AdminSitesSiteIdContentTypeSlugNewRouteImport } from './routes/_admin/sites.$siteId/content.$typeSlug/new'
import { Route as AdminSitesSiteIdContentTypeSlugIdEditRouteImport } from './routes/_admin/sites.$siteId/content.$typeSlug/$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesIndexRoute = AdminSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSitesRoute,
} as any)
const AdminSitesSiteIdRoute = AdminSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AdminSitesRoute,
} as any)
const AdminSitesSiteIdIndexRoute = AdminSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSitesSiteIdRoute,
} as any)
const AdminSitesSiteIdContentTypesRoute =
  AdminSitesSiteIdContentTypesRouteImport.update({
    id: '/content-types',
    path: '/content-types',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdContentTypeSlugRoute =
  AdminSitesSiteIdContentTypeSlugRouteImport.update({
    id: '/content/$typeSlug',
    path: '/content/$typeSlug',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdContentTypeSlugIndexRoute =
  AdminSitesSiteIdContentTypeSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSitesSiteIdContentTypeSlugRoute,
  } as any)
const AdminSitesSiteIdContentTypeSlugNewRoute =
  AdminSitesSiteIdContentTypeSlugNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSitesSiteIdContentTypeSlugRoute,
  } as any)
const AdminSitesSiteIdContentTypeSlugIdEditRoute =
  AdminSitesSiteIdContentTypeSlugIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminSitesSiteIdContentTypeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sites': typeof AdminSitesRouteWithChildren
  '/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/sites/': typeof AdminSitesIndexRoute
  '/sites/$siteId/content-types': typeof AdminSitesSiteIdContentTypesRoute
  '/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/content/$typeSlug': typeof AdminSitesSiteIdContentTypeSlugRouteWithChildren
  '/sites/$siteId/content/$typeSlug/new': typeof AdminSitesSiteIdContentTypeSlugNewRoute
  '/sites/$siteId/content/$typeSlug/': typeof AdminSitesSiteIdContentTypeSlugIndexRoute
  '/sites/$siteId/content/$typeSlug/$id/edit': typeof AdminSitesSiteIdContentTypeSlugIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AdminIndexRoute
  '/sites': typeof AdminSitesIndexRoute
  '/sites/$siteId/content-types': typeof AdminSitesSiteIdContentTypesRoute
  '/sites/$siteId': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/content/$typeSlug/new': typeof AdminSitesSiteIdContentTypeSlugNewRoute
  '/sites/$siteId/content/$typeSlug': typeof AdminSitesSiteIdContentTypeSlugIndexRoute
  '/sites/$siteId/content/$typeSlug/$id/edit': typeof AdminSitesSiteIdContentTypeSlugIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/sites': typeof AdminSitesRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/_admin/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/_admin/sites/': typeof AdminSitesIndexRoute
  '/_admin/sites/$siteId/content-types': typeof AdminSitesSiteIdContentTypesRoute
  '/_admin/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/_admin/sites/$siteId/content/$typeSlug': typeof AdminSitesSiteIdContentTypeSlugRouteWithChildren
  '/_admin/sites/$siteId/content/$typeSlug/new': typeof AdminSitesSiteIdContentTypeSlugNewRoute
  '/_admin/sites/$siteId/content/$typeSlug/': typeof AdminSitesSiteIdContentTypeSlugIndexRoute
  '/_admin/sites/$siteId/content/$typeSlug/$id/edit': typeof AdminSitesSiteIdContentTypeSlugIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sites'
    | '/sites/$siteId'
    | '/sites/'
    | '/sites/$siteId/content-types'
    | '/sites/$siteId/'
    | '/sites/$siteId/content/$typeSlug'
    | '/sites/$siteId/content/$typeSlug/new'
    | '/sites/$siteId/content/$typeSlug/'
    | '/sites/$siteId/content/$typeSlug/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/sites'
    | '/sites/$siteId/content-types'
    | '/sites/$siteId'
    | '/sites/$siteId/content/$typeSlug/new'
    | '/sites/$siteId/content/$typeSlug'
    | '/sites/$siteId/content/$typeSlug/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_admin/sites'
    | '/_admin/'
    | '/_admin/sites/$siteId'
    | '/_admin/sites/'
    | '/_admin/sites/$siteId/content-types'
    | '/_admin/sites/$siteId/'
    | '/_admin/sites/$siteId/content/$typeSlug'
    | '/_admin/sites/$siteId/content/$typeSlug/new'
    | '/_admin/sites/$siteId/content/$typeSlug/'
    | '/_admin/sites/$siteId/content/$typeSlug/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sites': {
      id: '/_admin/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sites/': {
      id: '/_admin/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof AdminSitesIndexRouteImport
      parentRoute: typeof AdminSitesRoute
    }
    '/_admin/sites/$siteId': {
      id: '/_admin/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AdminSitesSiteIdRouteImport
      parentRoute: typeof AdminSitesRoute
    }
    '/_admin/sites/$siteId/': {
      id: '/_admin/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AdminSitesSiteIdIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/content-types': {
      id: '/_admin/sites/$siteId/content-types'
      path: '/content-types'
      fullPath: '/sites/$siteId/content-types'
      preLoaderRoute: typeof AdminSitesSiteIdContentTypesRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/content/$typeSlug': {
      id: '/_admin/sites/$siteId/content/$typeSlug'
      path: '/content/$typeSlug'
      fullPath: '/sites/$siteId/content/$typeSlug'
      preLoaderRoute: typeof AdminSitesSiteIdContentTypeSlugRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/content/$typeSlug/': {
      id: '/_admin/sites/$siteId/content/$typeSlug/'
      path: '/'
      fullPath: '/sites/$siteId/content/$typeSlug/'
      preLoaderRoute: typeof AdminSitesSiteIdContentTypeSlugIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdContentTypeSlugRoute
    }
    '/_admin/sites/$siteId/content/$typeSlug/new': {
      id: '/_admin/sites/$siteId/content/$typeSlug/new'
      path: '/new'
      fullPath: '/sites/$siteId/content/$typeSlug/new'
      preLoaderRoute: typeof AdminSitesSiteIdContentTypeSlugNewRouteImport
      parentRoute: typeof AdminSitesSiteIdContentTypeSlugRoute
    }
    '/_admin/sites/$siteId/content/$typeSlug/$id/edit': {
      id: '/_admin/sites/$siteId/content/$typeSlug/$id/edit'
      path: '/$id/edit'
      fullPath: '/sites/$siteId/content/$typeSlug/$id/edit'
      preLoaderRoute: typeof AdminSitesSiteIdContentTypeSlugIdEditRouteImport
      parentRoute: typeof AdminSitesSiteIdContentTypeSlugRoute
    }
  }
}

interface AdminSitesSiteIdContentTypeSlugRouteChildren {
  AdminSitesSiteIdContentTypeSlugNewRoute: typeof AdminSitesSiteIdContentTypeSlugNewRoute
  AdminSitesSiteIdContentTypeSlugIndexRoute: typeof AdminSitesSiteIdContentTypeSlugIndexRoute
  AdminSitesSiteIdContentTypeSlugIdEditRoute: typeof AdminSitesSiteIdContentTypeSlugIdEditRoute
}

const AdminSitesSiteIdContentTypeSlugRouteChildren: AdminSitesSiteIdContentTypeSlugRouteChildren =
  {
    AdminSitesSiteIdContentTypeSlugNewRoute:
      AdminSitesSiteIdContentTypeSlugNewRoute,
    AdminSitesSiteIdContentTypeSlugIndexRoute:
      AdminSitesSiteIdContentTypeSlugIndexRoute,
    AdminSitesSiteIdContentTypeSlugIdEditRoute:
      AdminSitesSiteIdContentTypeSlugIdEditRoute,
  }

const AdminSitesSiteIdContentTypeSlugRouteWithChildren =
  AdminSitesSiteIdContentTypeSlugRoute._addFileChildren(
    AdminSitesSiteIdContentTypeSlugRouteChildren,
  )

interface AdminSitesSiteIdRouteChildren {
  AdminSitesSiteIdContentTypesRoute: typeof AdminSitesSiteIdContentTypesRoute
  AdminSitesSiteIdIndexRoute: typeof AdminSitesSiteIdIndexRoute
  AdminSitesSiteIdContentTypeSlugRoute: typeof AdminSitesSiteIdContentTypeSlugRouteWithChildren
}

const AdminSitesSiteIdRouteChildren: AdminSitesSiteIdRouteChildren = {
  AdminSitesSiteIdContentTypesRoute: AdminSitesSiteIdContentTypesRoute,
  AdminSitesSiteIdIndexRoute: AdminSitesSiteIdIndexRoute,
  AdminSitesSiteIdContentTypeSlugRoute:
    AdminSitesSiteIdContentTypeSlugRouteWithChildren,
}

const AdminSitesSiteIdRouteWithChildren =
  AdminSitesSiteIdRoute._addFileChildren(AdminSitesSiteIdRouteChildren)

interface AdminSitesRouteChildren {
  AdminSitesSiteIdRoute: typeof AdminSitesSiteIdRouteWithChildren
  AdminSitesIndexRoute: typeof AdminSitesIndexRoute
}

const AdminSitesRouteChildren: AdminSitesRouteChildren = {
  AdminSitesSiteIdRoute: AdminSitesSiteIdRouteWithChildren,
  AdminSitesIndexRoute: AdminSitesIndexRoute,
}

const AdminSitesRouteWithChildren = AdminSitesRoute._addFileChildren(
  AdminSitesRouteChildren,
)

interface AdminRouteChildren {
  AdminSitesRoute: typeof AdminSitesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSitesRoute: AdminSitesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
