/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminContentTypesRouteImport } from './routes/_admin/content-types'
import { Route as AdminContentTypeSlugRouteImport } from './routes/_admin/content.$typeSlug'
import { Route as AdminContentTypeSlugIndexRouteImport } from './routes/_admin/content.$typeSlug.index'
import { Route as AdminContentTypeSlugNewRouteImport } from './routes/_admin/content.$typeSlug.new'
import { Route as AdminContentTypeSlugIdEditRouteImport } from './routes/_admin/content.$typeSlug.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypesRoute = AdminContentTypesRouteImport.update({
  id: '/content-types',
  path: '/content-types',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypeSlugRoute = AdminContentTypeSlugRouteImport.update({
  id: '/content/$typeSlug',
  path: '/content/$typeSlug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTypeSlugIndexRoute =
  AdminContentTypeSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentTypeSlugRoute,
  } as any)
const AdminContentTypeSlugNewRoute = AdminContentTypeSlugNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentTypeSlugRoute,
} as any)
const AdminContentTypeSlugIdEditRoute =
  AdminContentTypeSlugIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminContentTypeSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/content-types': typeof AdminContentTypesRoute
  '/content/$typeSlug': typeof AdminContentTypeSlugRouteWithChildren
  '/content/$typeSlug/new': typeof AdminContentTypeSlugNewRoute
  '/content/$typeSlug/': typeof AdminContentTypeSlugIndexRoute
  '/content/$typeSlug/$id/edit': typeof AdminContentTypeSlugIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/content-types': typeof AdminContentTypesRoute
  '/': typeof AdminIndexRoute
  '/content/$typeSlug/new': typeof AdminContentTypeSlugNewRoute
  '/content/$typeSlug': typeof AdminContentTypeSlugIndexRoute
  '/content/$typeSlug/$id/edit': typeof AdminContentTypeSlugIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/content-types': typeof AdminContentTypesRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/content/$typeSlug': typeof AdminContentTypeSlugRouteWithChildren
  '/_admin/content/$typeSlug/new': typeof AdminContentTypeSlugNewRoute
  '/_admin/content/$typeSlug/': typeof AdminContentTypeSlugIndexRoute
  '/_admin/content/$typeSlug/$id/edit': typeof AdminContentTypeSlugIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/content-types'
    | '/content/$typeSlug'
    | '/content/$typeSlug/new'
    | '/content/$typeSlug/'
    | '/content/$typeSlug/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/content-types'
    | '/'
    | '/content/$typeSlug/new'
    | '/content/$typeSlug'
    | '/content/$typeSlug/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_admin/content-types'
    | '/_admin/'
    | '/_admin/content/$typeSlug'
    | '/_admin/content/$typeSlug/new'
    | '/_admin/content/$typeSlug/'
    | '/_admin/content/$typeSlug/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/content-types': {
      id: '/_admin/content-types'
      path: '/content-types'
      fullPath: '/content-types'
      preLoaderRoute: typeof AdminContentTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/content/$typeSlug': {
      id: '/_admin/content/$typeSlug'
      path: '/content/$typeSlug'
      fullPath: '/content/$typeSlug'
      preLoaderRoute: typeof AdminContentTypeSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/content/$typeSlug/': {
      id: '/_admin/content/$typeSlug/'
      path: '/'
      fullPath: '/content/$typeSlug/'
      preLoaderRoute: typeof AdminContentTypeSlugIndexRouteImport
      parentRoute: typeof AdminContentTypeSlugRoute
    }
    '/_admin/content/$typeSlug/new': {
      id: '/_admin/content/$typeSlug/new'
      path: '/new'
      fullPath: '/content/$typeSlug/new'
      preLoaderRoute: typeof AdminContentTypeSlugNewRouteImport
      parentRoute: typeof AdminContentTypeSlugRoute
    }
    '/_admin/content/$typeSlug/$id/edit': {
      id: '/_admin/content/$typeSlug/$id/edit'
      path: '/$id/edit'
      fullPath: '/content/$typeSlug/$id/edit'
      preLoaderRoute: typeof AdminContentTypeSlugIdEditRouteImport
      parentRoute: typeof AdminContentTypeSlugRoute
    }
  }
}

interface AdminContentTypeSlugRouteChildren {
  AdminContentTypeSlugNewRoute: typeof AdminContentTypeSlugNewRoute
  AdminContentTypeSlugIndexRoute: typeof AdminContentTypeSlugIndexRoute
  AdminContentTypeSlugIdEditRoute: typeof AdminContentTypeSlugIdEditRoute
}

const AdminContentTypeSlugRouteChildren: AdminContentTypeSlugRouteChildren = {
  AdminContentTypeSlugNewRoute: AdminContentTypeSlugNewRoute,
  AdminContentTypeSlugIndexRoute: AdminContentTypeSlugIndexRoute,
  AdminContentTypeSlugIdEditRoute: AdminContentTypeSlugIdEditRoute,
}

const AdminContentTypeSlugRouteWithChildren =
  AdminContentTypeSlugRoute._addFileChildren(AdminContentTypeSlugRouteChildren)

interface AdminRouteChildren {
  AdminContentTypesRoute: typeof AdminContentTypesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentTypeSlugRoute: typeof AdminContentTypeSlugRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentTypesRoute: AdminContentTypesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentTypeSlugRoute: AdminContentTypeSlugRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
