package repository

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"github.com/velopulent/cms/apps/backend-go/internal/application"
	"github.com/velopulent/cms/apps/backend-go/internal/domain"
	"github.com/velopulent/cms/apps/backend-go/internal/ports"
)

type SQLiteSiteRepository struct{ db *sql.DB }
type SQLiteCollectionRepository struct{ db *sql.DB }
type SQLiteEntryRepository struct{ db *sql.DB }
type SQLiteFileRepository struct{ db *sql.DB }
type SQLiteAccessTokenRepository struct{ db *sql.DB }

func NewSQLiteSiteRepository(db *sql.DB) *SQLiteSiteRepository { return &SQLiteSiteRepository{db} }
func NewSQLiteCollectionRepository(db *sql.DB) *SQLiteCollectionRepository { return &SQLiteCollectionRepository{db} }
func NewSQLiteEntryRepository(db *sql.DB) *SQLiteEntryRepository { return &SQLiteEntryRepository{db} }
func NewSQLiteFileRepository(db *sql.DB) *SQLiteFileRepository { return &SQLiteFileRepository{db} }
func NewSQLiteAccessTokenRepository(db *sql.DB) *SQLiteAccessTokenRepository { return &SQLiteAccessTokenRepository{db} }

func (r *SQLiteSiteRepository) ListAll(ctx context.Context) ([]domain.Site, error) {
	rows, err := r.db.QueryContext(ctx, "SELECT id,name,storage_provider,created_by,created_at,updated_at FROM sites ORDER BY created_at DESC")
	if err != nil { return nil, err }
	defer rows.Close()
	var out []domain.Site
	for rows.Next() { var s domain.Site; if err := rows.Scan(&s.ID,&s.Name,&s.StorageProvider,&s.CreatedBy,&s.CreatedAt,&s.UpdatedAt); err != nil { return nil, err }; out=append(out,s) }
	return out, rows.Err()
}
func (r *SQLiteSiteRepository) ListForUser(ctx context.Context, userID string) ([]domain.SiteWithRole, error) {
	rows, err := r.db.QueryContext(ctx, `SELECT s.id,s.name,s.storage_provider,s.created_by,s.created_at,s.updated_at,sm.role FROM sites s JOIN site_members sm ON sm.site_id=s.id WHERE sm.user_id=? ORDER BY s.created_at DESC`, userID)
	if err != nil { return nil, err }; defer rows.Close(); var out []domain.SiteWithRole
	for rows.Next() { var s domain.SiteWithRole; if err:=rows.Scan(&s.ID,&s.Name,&s.StorageProvider,&s.CreatedBy,&s.CreatedAt,&s.UpdatedAt,&s.Role); err!=nil { return nil, err }; out=append(out,s) }
	return out, rows.Err()
}
func (r *SQLiteSiteRepository) GetByID(ctx context.Context, id string) (*domain.Site, error) {
	var s domain.Site; err := r.db.QueryRowContext(ctx, "SELECT id,name,storage_provider,created_by,created_at,updated_at FROM sites WHERE id=?", id).Scan(&s.ID,&s.Name,&s.StorageProvider,&s.CreatedBy,&s.CreatedAt,&s.UpdatedAt)
	if errors.Is(err, sql.ErrNoRows) { return nil, nil }; if err != nil { return nil, err }; return &s, nil
}
func (r *SQLiteSiteRepository) Create(ctx context.Context, id, name, storageProvider, createdBy string) (*domain.Site, error) {
	if _, err := r.db.ExecContext(ctx, "INSERT INTO sites(id,name,storage_provider,created_by) VALUES(?,?,?,?)", id,name,storageProvider,createdBy); err != nil { return nil, err }
	_, _ = r.db.ExecContext(ctx, "INSERT OR IGNORE INTO site_members(id,site_id,user_id,role) VALUES(?,?,?,?)", id+"-member", id, createdBy, "owner")
	return r.GetByID(ctx,id)
}
func (r *SQLiteSiteRepository) Update(ctx context.Context, id, name string) (*domain.Site, error) { _, err:=r.db.ExecContext(ctx,"UPDATE sites SET name=?, updated_at=datetime('now') WHERE id=?",name,id); if err!=nil{return nil,err}; return r.GetByID(ctx,id) }
func (r *SQLiteSiteRepository) Delete(ctx context.Context, id string) (int64,error) { res,err:=r.db.ExecContext(ctx,"DELETE FROM sites WHERE id=?",id); if err!=nil{return 0,err}; return res.RowsAffected() }
func (r *SQLiteSiteRepository) ListMembers(ctx context.Context, siteID string) ([]domain.SiteMember,error){ rows,err:=r.db.QueryContext(ctx,`SELECT sm.id,sm.site_id,sm.user_id,u.username,u.email,sm.role,sm.created_at FROM site_members sm JOIN users u ON u.id=sm.user_id WHERE sm.site_id=? ORDER BY sm.created_at`,siteID); if err!=nil{return nil,err}; defer rows.Close(); var out []domain.SiteMember; for rows.Next(){var m domain.SiteMember; if err:=rows.Scan(&m.ID,&m.SiteID,&m.UserID,&m.Username,&m.Email,&m.Role,&m.CreatedAt);err!=nil{return nil,err}; out=append(out,m)}; return out, rows.Err() }
func (r *SQLiteSiteRepository) AddMember(ctx context.Context,id,siteID,userID,role string)(*domain.SiteMember,error){ _,err:=r.db.ExecContext(ctx,"INSERT INTO site_members(id,site_id,user_id,role) VALUES(?,?,?,?)",id,siteID,userID,role); if err!=nil{ if isSQLiteUniqueViolation(err){return nil,application.ErrDuplicateUser}; return nil,err}; return r.member(ctx,siteID,userID) }
func (r *SQLiteSiteRepository) UpdateMemberRole(ctx context.Context,siteID,userID,role string)(*domain.SiteMember,error){ res,err:=r.db.ExecContext(ctx,"UPDATE site_members SET role=? WHERE site_id=? AND user_id=?",role,siteID,userID); if err!=nil{return nil,err}; n,_:=res.RowsAffected(); if n==0{return nil,nil}; return r.member(ctx,siteID,userID) }
func (r *SQLiteSiteRepository) member(ctx context.Context,siteID,userID string)(*domain.SiteMember,error){ ms,err:=r.ListMembers(ctx,siteID); if err!=nil{return nil,err}; for _,m:=range ms{if m.UserID==userID{return &m,nil}}; return nil,nil }
func (r *SQLiteSiteRepository) RemoveMember(ctx context.Context,siteID,userID string)(int64,error){ res,err:=r.db.ExecContext(ctx,"DELETE FROM site_members WHERE site_id=? AND user_id=?",siteID,userID); if err!=nil{return 0,err}; return res.RowsAffected() }

func (r *SQLiteCollectionRepository) List(ctx context.Context, siteID string) ([]domain.Collection,error){ return r.list(ctx,"SELECT id,site_id,name,slug,definition,is_singleton,singleton_data,created_at,updated_at FROM collections WHERE site_id=? ORDER BY created_at DESC",siteID) }
func (r *SQLiteCollectionRepository) ListSingletons(ctx context.Context,siteID string)([]domain.Collection,error){ return r.list(ctx,"SELECT id,site_id,name,slug,definition,is_singleton,singleton_data,created_at,updated_at FROM collections WHERE site_id=? AND is_singleton=1 ORDER BY created_at DESC",siteID) }
func (r *SQLiteCollectionRepository) list(ctx context.Context,q string,args ...any)([]domain.Collection,error){ rows,err:=r.db.QueryContext(ctx,q,args...); if err!=nil{return nil,err}; defer rows.Close(); var out []domain.Collection; for rows.Next(){var c domain.Collection; var b int; if err:=rows.Scan(&c.ID,&c.SiteID,&c.Name,&c.Slug,&c.Definition,&b,&c.SingletonData,&c.CreatedAt,&c.UpdatedAt);err!=nil{return nil,err}; c.IsSingleton=b!=0; out=append(out,c)}; return out, rows.Err() }
func (r *SQLiteCollectionRepository) GetBySlug(ctx context.Context,siteID,slug string)(*domain.Collection,error){ cs,err:=r.list(ctx,"SELECT id,site_id,name,slug,definition,is_singleton,singleton_data,created_at,updated_at FROM collections WHERE site_id=? AND slug=?",siteID,slug); if err!=nil||len(cs)==0{return nil,err}; return &cs[0],nil }
func (r *SQLiteCollectionRepository) GetByID(ctx context.Context,id string)(*domain.Collection,error){ cs,err:=r.list(ctx,"SELECT id,site_id,name,slug,definition,is_singleton,singleton_data,created_at,updated_at FROM collections WHERE id=?",id); if err!=nil||len(cs)==0{return nil,err}; return &cs[0],nil }
func (r *SQLiteCollectionRepository) Create(ctx context.Context,id,siteID,name,slug,definition string,singleton bool)(*domain.Collection,error){ b:=0;if singleton{b=1}; _,err:=r.db.ExecContext(ctx,"INSERT INTO collections(id,site_id,name,slug,definition,is_singleton) VALUES(?,?,?,?,?,?)",id,siteID,name,slug,definition,b); if err!=nil{if isSQLiteUniqueViolation(err){return nil,application.ErrDuplicateUser}; return nil,err}; return r.GetByID(ctx,id) }
func (r *SQLiteCollectionRepository) Update(ctx context.Context,id,name,slug,definition string)(*domain.Collection,error){ _,err:=r.db.ExecContext(ctx,"UPDATE collections SET name=?, slug=?, definition=?, updated_at=datetime('now') WHERE id=?",name,slug,definition,id); if err!=nil{return nil,err}; return r.GetByID(ctx,id) }
func (r *SQLiteCollectionRepository) UpdateSingletonData(ctx context.Context,id,data string)(*domain.Collection,error){ _,err:=r.db.ExecContext(ctx,"UPDATE collections SET singleton_data=?, updated_at=datetime('now') WHERE id=?",data,id); if err!=nil{return nil,err}; return r.GetByID(ctx,id) }
func (r *SQLiteCollectionRepository) Delete(ctx context.Context,siteID,slug string)(int64,error){ res,err:=r.db.ExecContext(ctx,"DELETE FROM collections WHERE site_id=? AND slug=?",siteID,slug); if err!=nil{return 0,err}; return res.RowsAffected() }

func (r *SQLiteEntryRepository) GetByIDAnySite(ctx context.Context,id string)(*domain.Entry,error){ return r.scan(ctx,"SELECT id,site_id,collection_id,data,slug,status,created_at,updated_at,published_at FROM entries WHERE id=?",id) }
func (r *SQLiteEntryRepository) GetByID(ctx context.Context,id,siteID string,publishedOnly bool)(*domain.Entry,error){ q:="SELECT id,site_id,collection_id,data,slug,status,created_at,updated_at,published_at FROM entries WHERE id=? AND site_id=?"; args:=[]any{id,siteID}; if publishedOnly{q+=" AND status='published'"}; return r.scan(ctx,q,args...) }
func (r *SQLiteEntryRepository) scan(ctx context.Context,q string,args ...any)(*domain.Entry,error){ var e domain.Entry; err:=r.db.QueryRowContext(ctx,q,args...).Scan(&e.ID,&e.SiteID,&e.CollectionID,&e.Data,&e.Slug,&e.Status,&e.CreatedAt,&e.UpdatedAt,&e.PublishedAt); if errors.Is(err,sql.ErrNoRows){return nil,nil}; if err!=nil{return nil,err}; return &e,nil }
func (r *SQLiteEntryRepository) List(ctx context.Context,p ports.ListEntriesParams)(domain.EntriesListResult,error){ where:=[]string{"e.site_id=?"}; args:=[]any{p.SiteID}; if p.CollectionID!=""{where=append(where,"e.collection_id=?");args=append(args,p.CollectionID)}; if p.CollectionSlug!=""{where=append(where,"c.slug=?");args=append(args,p.CollectionSlug)}; if p.Status!=""{where=append(where,"e.status=?");args=append(args,p.Status)}; if p.PublishedOnly{where=append(where,"e.status='published'")}; if p.Search!=""{where=append(where,"(e.slug LIKE ? OR e.data LIKE ?)");args=append(args,"%"+p.Search+"%","%"+p.Search+"%")}; wc:=strings.Join(where," AND "); var total int64; _=r.db.QueryRowContext(ctx,"SELECT COUNT(*) FROM entries e JOIN collections c ON c.id=e.collection_id WHERE "+wc,args...).Scan(&total); page,per:=p.Page,p.PerPage;if page<1{page=1};if per<1{per=50}; rows,err:=r.db.QueryContext(ctx,"SELECT e.id,e.site_id,e.collection_id,e.data,e.slug,e.status,e.created_at,e.updated_at,e.published_at FROM entries e JOIN collections c ON c.id=e.collection_id WHERE "+wc+" ORDER BY e.updated_at DESC LIMIT ? OFFSET ?",append(args,per,(page-1)*per)...); if err!=nil{return domain.EntriesListResult{},err}; defer rows.Close(); var items []domain.Entry; for rows.Next(){var e domain.Entry;if err:=rows.Scan(&e.ID,&e.SiteID,&e.CollectionID,&e.Data,&e.Slug,&e.Status,&e.CreatedAt,&e.UpdatedAt,&e.PublishedAt);err!=nil{return domain.EntriesListResult{},err};items=append(items,e)}; return domain.EntriesListResult{Items:items,Total:total,Page:page,PerPage:per},rows.Err() }
func (r *SQLiteEntryRepository) Create(ctx context.Context,id,siteID,collectionID,data,slug string,createdBy *string)(*domain.Entry,error){ _,err:=r.db.ExecContext(ctx,"INSERT INTO entries(id,site_id,collection_id,data,slug) VALUES(?,?,?,?,?)",id,siteID,collectionID,data,slug); if err!=nil{if isSQLiteUniqueViolation(err){return nil,application.ErrDuplicateUser};return nil,err}; _=r.createRevision(ctx,id,data,createdBy,nil); return r.GetByID(ctx,id,siteID,false) }
func (r *SQLiteEntryRepository) Update(ctx context.Context,id,siteID,data,slug,status string,createdBy *string,summary *string)(*domain.Entry,error){ _,err:=r.db.ExecContext(ctx,"UPDATE entries SET data=?,slug=?,status=?,updated_at=datetime('now'),published_at=CASE WHEN ?='published' THEN COALESCE(published_at, datetime('now')) ELSE published_at END WHERE id=? AND site_id=?",data,slug,status,status,id,siteID); if err!=nil{if isSQLiteUniqueViolation(err){return nil,application.ErrDuplicateUser};return nil,err}; _=r.createRevision(ctx,id,data,createdBy,summary); return r.GetByID(ctx,id,siteID,false) }
func (r *SQLiteEntryRepository) createRevision(ctx context.Context,entryID,data string,createdBy,summary *string) error { var n int64; _=r.db.QueryRowContext(ctx,"SELECT COALESCE(MAX(revision_number),0)+1 FROM entry_revisions WHERE entry_id=?",entryID).Scan(&n); _,err:=r.db.ExecContext(ctx,"INSERT INTO entry_revisions(id,entry_id,revision_number,data,created_by,change_summary) VALUES(?,?,?,?,?,?)",entryID+fmt.Sprint(n),entryID,n,data,createdBy,summary); return err }
func (r *SQLiteEntryRepository) Delete(ctx context.Context,id,siteID string)(int64,error){res,err:=r.db.ExecContext(ctx,"DELETE FROM entries WHERE id=? AND site_id=?",id,siteID); if err!=nil{return 0,err}; return res.RowsAffected()}
func (r *SQLiteEntryRepository) Publish(ctx context.Context,id,siteID string)(*domain.Entry,error){res,err:=r.db.ExecContext(ctx,"UPDATE entries SET status='published', published_at=COALESCE(published_at, datetime('now')), updated_at=datetime('now') WHERE id=? AND site_id=?",id,siteID); if err!=nil{return nil,err}; n,_:=res.RowsAffected(); if n==0{return nil,application.ErrNotFound}; return r.GetByID(ctx,id,siteID,false)}
func (r *SQLiteEntryRepository) Unpublish(ctx context.Context,id,siteID string)(*domain.Entry,error){res,err:=r.db.ExecContext(ctx,"UPDATE entries SET status='draft', updated_at=datetime('now') WHERE id=? AND site_id=?",id,siteID); if err!=nil{return nil,err}; n,_:=res.RowsAffected(); if n==0{return nil,application.ErrNotFound}; return r.GetByID(ctx,id,siteID,false)}
func (r *SQLiteEntryRepository) SyncFileReferences(ctx context.Context,entryID,siteID string,data []byte)error{_,_ = r.db.ExecContext(ctx,"DELETE FROM entry_file_references WHERE entry_id=?",entryID); for _,id:=range application.ExtractFileIDs(data){_,_=r.db.ExecContext(ctx,"INSERT OR IGNORE INTO entry_file_references(entry_id,file_id,site_id) VALUES(?,?,?)",entryID,id,siteID)}; return nil}
func (r *SQLiteEntryRepository) ListRevisions(ctx context.Context,entryID string,page,perPage int64)(domain.RevisionsListResult,error){if page<1{page=1};if perPage<1{perPage=50}; var total int64; _=r.db.QueryRowContext(ctx,"SELECT COUNT(*) FROM entry_revisions WHERE entry_id=?",entryID).Scan(&total); rows,err:=r.db.QueryContext(ctx,"SELECT id,entry_id,revision_number,data,created_by,created_at,change_summary FROM entry_revisions WHERE entry_id=? ORDER BY revision_number DESC LIMIT ? OFFSET ?",entryID,perPage,(page-1)*perPage); if err!=nil{return domain.RevisionsListResult{},err}; defer rows.Close(); var items []domain.EntryRevision; for rows.Next(){var v domain.EntryRevision; if err:=rows.Scan(&v.ID,&v.EntryID,&v.RevisionNumber,&v.Data,&v.CreatedBy,&v.CreatedAt,&v.ChangeSummary);err!=nil{return domain.RevisionsListResult{},err}; items=append(items,v)}; return domain.RevisionsListResult{Items:items,Total:total,Page:page,PerPage:perPage},rows.Err()}
func (r *SQLiteEntryRepository) GetRevision(ctx context.Context,entryID string,number int64)(*domain.EntryRevision,error){var v domain.EntryRevision; err:=r.db.QueryRowContext(ctx,"SELECT id,entry_id,revision_number,data,created_by,created_at,change_summary FROM entry_revisions WHERE entry_id=? AND revision_number=?",entryID,number).Scan(&v.ID,&v.EntryID,&v.RevisionNumber,&v.Data,&v.CreatedBy,&v.CreatedAt,&v.ChangeSummary); if errors.Is(err,sql.ErrNoRows){return nil,nil}; if err!=nil{return nil,err}; return &v,nil}
func (r *SQLiteEntryRepository) RestoreRevision(ctx context.Context,entryID string,number int64,createdBy *string)(*domain.Entry,error){rev,err:=r.GetRevision(ctx,entryID,number); if err!=nil||rev==nil{return nil,application.ErrNotFound}; e,err:=r.GetByIDAnySite(ctx,entryID); if err!=nil||e==nil{return nil,application.ErrNotFound}; sum:=fmt.Sprintf("Restored revision %d",number); return r.Update(ctx,entryID,e.SiteID,rev.Data,e.Slug,e.Status,createdBy,&sum)}

func (r *SQLiteFileRepository) GetByID(ctx context.Context,id,siteID string)(*domain.File,error){return r.scan(ctx,"SELECT id,site_id,filename,original_name,mime_type,size,storage_provider,storage_key,thumbnail_key,width,height,deleted_at,created_by,created_at FROM files WHERE id=? AND site_id=?",id,siteID)}
func (r *SQLiteFileRepository) GetByIDAny(ctx context.Context,id string)(*domain.File,error){return r.scan(ctx,"SELECT id,site_id,filename,original_name,mime_type,size,storage_provider,storage_key,thumbnail_key,width,height,deleted_at,created_by,created_at FROM files WHERE id=?",id)}
func (r *SQLiteFileRepository) scan(ctx context.Context,q string,args ...any)(*domain.File,error){var f domain.File; err:=r.db.QueryRowContext(ctx,q,args...).Scan(&f.ID,&f.SiteID,&f.Filename,&f.OriginalName,&f.MimeType,&f.Size,&f.StorageProvider,&f.StorageKey,&f.ThumbnailKey,&f.Width,&f.Height,&f.DeletedAt,&f.CreatedBy,&f.CreatedAt); if errors.Is(err,sql.ErrNoRows){return nil,nil}; if err!=nil{return nil,err}; return &f,nil}
func (r *SQLiteFileRepository) List(ctx context.Context,p ports.ListFilesParams)(domain.FileListResult,error){where:=[]string{"site_id=?"}; args:=[]any{p.SiteID}; if p.Trashed{where=append(where,"deleted_at IS NOT NULL")}else{where=append(where,"deleted_at IS NULL")}; if p.Search!=""{where=append(where,"(filename LIKE ? OR original_name LIKE ?)");args=append(args,"%"+p.Search+"%","%"+p.Search+"%")}; if p.FileType!=""{where=append(where,"mime_type LIKE ?");args=append(args,p.FileType+"%")}; wc:=strings.Join(where," AND "); var total int64; _=r.db.QueryRowContext(ctx,"SELECT COUNT(*) FROM files WHERE "+wc,args...).Scan(&total); page,per:=p.Page,p.PerPage;if page<1{page=1};if per<1{per=30}; rows,err:=r.db.QueryContext(ctx,"SELECT id,site_id,filename,original_name,mime_type,size,storage_provider,storage_key,thumbnail_key,width,height,deleted_at,created_by,created_at FROM files WHERE "+wc+" ORDER BY created_at DESC LIMIT ? OFFSET ?",append(args,per,(page-1)*per)...); if err!=nil{return domain.FileListResult{},err}; defer rows.Close(); var items []domain.File; for rows.Next(){var f domain.File;if err:=rows.Scan(&f.ID,&f.SiteID,&f.Filename,&f.OriginalName,&f.MimeType,&f.Size,&f.StorageProvider,&f.StorageKey,&f.ThumbnailKey,&f.Width,&f.Height,&f.DeletedAt,&f.CreatedBy,&f.CreatedAt);err!=nil{return domain.FileListResult{},err};items=append(items,f)}; return domain.FileListResult{Items:items,Total:total,Page:page,PerPage:per},rows.Err()}
func (r *SQLiteFileRepository) Create(ctx context.Context,f domain.File)(*domain.File,error){_,err:=r.db.ExecContext(ctx,"INSERT INTO files(id,site_id,filename,original_name,mime_type,size,storage_provider,storage_key,thumbnail_key,width,height,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",f.ID,f.SiteID,f.Filename,f.OriginalName,f.MimeType,f.Size,f.StorageProvider,f.StorageKey,f.ThumbnailKey,f.Width,f.Height,f.CreatedBy); if err!=nil{return nil,err}; return r.GetByID(ctx,f.ID,f.SiteID)}
func (r *SQLiteFileRepository) SoftDelete(ctx context.Context,id,siteID string)(int64,error){res,err:=r.db.ExecContext(ctx,"UPDATE files SET deleted_at=datetime('now') WHERE id=? AND site_id=? AND deleted_at IS NULL",id,siteID); if err!=nil{return 0,err};return res.RowsAffected()}
func (r *SQLiteFileRepository) Restore(ctx context.Context,id,siteID string)(int64,error){res,err:=r.db.ExecContext(ctx,"UPDATE files SET deleted_at=NULL WHERE id=? AND site_id=? AND deleted_at IS NOT NULL",id,siteID); if err!=nil{return 0,err};return res.RowsAffected()}
func (r *SQLiteFileRepository) BatchSoftDelete(ctx context.Context,siteID string,ids []string)(int64,error){return r.batch(ctx,"UPDATE files SET deleted_at=datetime('now') WHERE site_id=? AND deleted_at IS NULL",siteID,ids)}
func (r *SQLiteFileRepository) BatchRestore(ctx context.Context,siteID string,ids []string)(int64,error){return r.batch(ctx,"UPDATE files SET deleted_at=NULL WHERE site_id=? AND deleted_at IS NOT NULL",siteID,ids)}
func (r *SQLiteFileRepository) BatchPermanentDelete(ctx context.Context,siteID string,ids []string)(int64,error){return r.batch(ctx,"DELETE FROM files WHERE site_id=?",siteID,ids)}
func (r *SQLiteFileRepository) batch(ctx context.Context,base,siteID string,ids []string)(int64,error){var total int64; for _,id:=range ids{res,err:=r.db.ExecContext(ctx,base+" AND id=?",siteID,id); if err!=nil{return total,err}; n,_:=res.RowsAffected(); total+=n}; return total,nil}
func (r *SQLiteFileRepository) GetByIDs(ctx context.Context,siteID string,ids []string,deletedOnly bool)([]domain.File,error){var out []domain.File; for _,id:=range ids{f,err:=r.GetByID(ctx,id,siteID); if err!=nil{return nil,err}; if f!=nil && (!deletedOnly || f.DeletedAt!=nil){out=append(out,*f)}}; return out,nil}
func (r *SQLiteFileRepository) GetReferencesForSite(ctx context.Context,fileID,siteID string)([]domain.FileReference,error){rows,err:=r.db.QueryContext(ctx,`SELECT e.id,c.name,'' FROM entry_file_references r JOIN entries e ON e.id=r.entry_id JOIN collections c ON c.id=e.collection_id WHERE r.file_id=? AND r.site_id=?`,fileID,siteID); if err!=nil{return nil,err}; defer rows.Close(); var out []domain.FileReference; for rows.Next(){var fr domain.FileReference; if err:=rows.Scan(&fr.EntryID,&fr.CollectionName,&fr.FieldName);err!=nil{return nil,err}; out=append(out,fr)}; return out,rows.Err()}
func (r *SQLiteFileRepository) GetStorageProvider(ctx context.Context,siteID string)(string,error){var v string; err:=r.db.QueryRowContext(ctx,"SELECT storage_provider FROM sites WHERE id=?",siteID).Scan(&v); if errors.Is(err,sql.ErrNoRows){return "filesystem",nil}; return v,err}

func (r *SQLiteAccessTokenRepository) List(ctx context.Context,kind string,siteID *string)([]domain.AccessToken,error){q:="SELECT id,kind,site_id,name,token_prefix,scopes,created_by_user_id,last_used_at,created_at,expires_at,revoked_at,token_hmac FROM access_tokens WHERE kind=?"; args:=[]any{kind}; if siteID!=nil{q+=" AND site_id=?";args=append(args,*siteID)}else{q+=" AND site_id IS NULL"}; rows,err:=r.db.QueryContext(ctx,q,args...); if err!=nil{return nil,err}; defer rows.Close(); return scanTokens(rows)}
func (r *SQLiteAccessTokenRepository) Create(ctx context.Context,t domain.AccessToken,hash string)error{_,err:=r.db.ExecContext(ctx,"INSERT INTO access_tokens(id,kind,site_id,name,token_hash,token_prefix,token_hmac,scopes,created_by_user_id) VALUES(?,?,?,?,?,?,?,?,?)",t.ID,t.Kind,t.SiteID,t.Name,hash,t.TokenPrefix,t.TokenHMAC,t.Scopes,t.CreatedByUserID);return err}
func (r *SQLiteAccessTokenRepository) Delete(ctx context.Context,id,kind string,siteID *string)(int64,error){q:="DELETE FROM access_tokens WHERE id=? AND kind=?"; args:=[]any{id,kind}; if siteID!=nil{q+=" AND site_id=?";args=append(args,*siteID)}else{q+=" AND site_id IS NULL"}; res,err:=r.db.ExecContext(ctx,q,args...); if err!=nil{return 0,err}; return res.RowsAffected()}
func (r *SQLiteAccessTokenRepository) FindByPrefix(ctx context.Context,prefix string)([]domain.AccessToken,error){rows,err:=r.db.QueryContext(ctx,"SELECT id,kind,site_id,name,token_prefix,scopes,created_by_user_id,last_used_at,created_at,expires_at,revoked_at,token_hmac FROM access_tokens WHERE token_prefix=?",prefix); if err!=nil{return nil,err}; defer rows.Close(); return scanTokens(rows)}
func (r *SQLiteAccessTokenRepository) UpdateLastUsed(ctx context.Context,id string)error{_,err:=r.db.ExecContext(ctx,"UPDATE access_tokens SET last_used_at=datetime('now') WHERE id=?",id); return err}
func scanTokens(rows *sql.Rows)([]domain.AccessToken,error){var out []domain.AccessToken; for rows.Next(){var t domain.AccessToken; if err:=rows.Scan(&t.ID,&t.Kind,&t.SiteID,&t.Name,&t.TokenPrefix,&t.Scopes,&t.CreatedByUserID,&t.LastUsedAt,&t.CreatedAt,&t.ExpiresAt,&t.RevokedAt,&t.TokenHMAC);err!=nil{return nil,err}; out=append(out,t)}; return out,rows.Err()}
