/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminSitesRouteImport } from './routes/_admin/sites'
import { Route as AdminSitesIndexRouteImport } from './routes/_admin/sites/index'
import { Route as AdminSitesSiteIdRouteImport } from './routes/_admin/sites.$siteId'
import { Route as AdminSitesSiteIdIndexRouteImport } from './routes/_admin/sites.$siteId/index'
import { Route as AdminSitesSiteIdSettingsRouteImport } from './routes/_admin/sites.$siteId/settings'
import { Route as AdminSitesSiteIdFilesRouteImport } from './routes/_admin/sites.$siteId/files'
import { Route as AdminSitesSiteIdCollectionsRouteImport } from './routes/_admin/sites.$siteId/collections'
import { Route as AdminSitesSiteIdSingletonsSlugRouteImport } from './routes/_admin/sites.$siteId/singletons.$slug'
import { Route as AdminSitesSiteIdEntriesCollectionSlugRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug'
import { Route as AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/index'
import { Route as AdminSitesSiteIdEntriesCollectionSlugNewRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/new'
import { Route as AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesIndexRoute = AdminSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSitesRoute,
} as any)
const AdminSitesSiteIdRoute = AdminSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AdminSitesRoute,
} as any)
const AdminSitesSiteIdIndexRoute = AdminSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSitesSiteIdRoute,
} as any)
const AdminSitesSiteIdSettingsRoute =
  AdminSitesSiteIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdFilesRoute = AdminSitesSiteIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminSitesSiteIdRoute,
} as any)
const AdminSitesSiteIdCollectionsRoute =
  AdminSitesSiteIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdSingletonsSlugRoute =
  AdminSitesSiteIdSingletonsSlugRouteImport.update({
    id: '/singletons/$slug',
    path: '/singletons/$slug',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugRoute =
  AdminSitesSiteIdEntriesCollectionSlugRouteImport.update({
    id: '/entries/$collectionSlug',
    path: '/entries/$collectionSlug',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugIndexRoute =
  AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugNewRoute =
  AdminSitesSiteIdEntriesCollectionSlugNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugIdEditRoute =
  AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sites': typeof AdminSitesRouteWithChildren
  '/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/sites/': typeof AdminSitesIndexRoute
  '/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsRoute
  '/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  '/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/sites/$siteId/entries/$collectionSlug/': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AdminIndexRoute
  '/sites': typeof AdminSitesIndexRoute
  '/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsRoute
  '/sites/$siteId': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/sites': typeof AdminSitesRouteWithChildren
  '/_admin/': typeof AdminIndexRoute
  '/_admin/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/_admin/sites/': typeof AdminSitesIndexRoute
  '/_admin/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/_admin/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/_admin/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsRoute
  '/_admin/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/_admin/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  '/_admin/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sites'
    | '/sites/$siteId'
    | '/sites/'
    | '/sites/$siteId/collections'
    | '/sites/$siteId/files'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/'
    | '/sites/$siteId/entries/$collectionSlug'
    | '/sites/$siteId/singletons/$slug'
    | '/sites/$siteId/entries/$collectionSlug/new'
    | '/sites/$siteId/entries/$collectionSlug/'
    | '/sites/$siteId/entries/$collectionSlug/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/sites'
    | '/sites/$siteId/collections'
    | '/sites/$siteId/files'
    | '/sites/$siteId/settings'
    | '/sites/$siteId'
    | '/sites/$siteId/singletons/$slug'
    | '/sites/$siteId/entries/$collectionSlug/new'
    | '/sites/$siteId/entries/$collectionSlug'
    | '/sites/$siteId/entries/$collectionSlug/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_admin/sites'
    | '/_admin/'
    | '/_admin/sites/$siteId'
    | '/_admin/sites/'
    | '/_admin/sites/$siteId/collections'
    | '/_admin/sites/$siteId/files'
    | '/_admin/sites/$siteId/settings'
    | '/_admin/sites/$siteId/'
    | '/_admin/sites/$siteId/entries/$collectionSlug'
    | '/_admin/sites/$siteId/singletons/$slug'
    | '/_admin/sites/$siteId/entries/$collectionSlug/new'
    | '/_admin/sites/$siteId/entries/$collectionSlug/'
    | '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sites': {
      id: '/_admin/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/sites/': {
      id: '/_admin/sites/'
      path: '/'
      fullPath: '/sites/'
      preLoaderRoute: typeof AdminSitesIndexRouteImport
      parentRoute: typeof AdminSitesRoute
    }
    '/_admin/sites/$siteId': {
      id: '/_admin/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AdminSitesSiteIdRouteImport
      parentRoute: typeof AdminSitesRoute
    }
    '/_admin/sites/$siteId/': {
      id: '/_admin/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AdminSitesSiteIdIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/settings': {
      id: '/_admin/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/files': {
      id: '/_admin/sites/$siteId/files'
      path: '/files'
      fullPath: '/sites/$siteId/files'
      preLoaderRoute: typeof AdminSitesSiteIdFilesRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/collections': {
      id: '/_admin/sites/$siteId/collections'
      path: '/collections'
      fullPath: '/sites/$siteId/collections'
      preLoaderRoute: typeof AdminSitesSiteIdCollectionsRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/singletons/$slug': {
      id: '/_admin/sites/$siteId/singletons/$slug'
      path: '/singletons/$slug'
      fullPath: '/sites/$siteId/singletons/$slug'
      preLoaderRoute: typeof AdminSitesSiteIdSingletonsSlugRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug'
      path: '/entries/$collectionSlug'
      fullPath: '/sites/$siteId/entries/$collectionSlug'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/'
      path: '/'
      fullPath: '/sites/$siteId/entries/$collectionSlug/'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/new': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/new'
      path: '/new'
      fullPath: '/sites/$siteId/entries/$collectionSlug/new'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugNewRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit'
      path: '/$id/edit'
      fullPath: '/sites/$siteId/entries/$collectionSlug/$id/edit'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
  }
}

interface AdminSitesSiteIdEntriesCollectionSlugRouteChildren {
  AdminSitesSiteIdEntriesCollectionSlugNewRoute: typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  AdminSitesSiteIdEntriesCollectionSlugIndexRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  AdminSitesSiteIdEntriesCollectionSlugIdEditRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}

const AdminSitesSiteIdEntriesCollectionSlugRouteChildren: AdminSitesSiteIdEntriesCollectionSlugRouteChildren =
  {
    AdminSitesSiteIdEntriesCollectionSlugNewRoute:
      AdminSitesSiteIdEntriesCollectionSlugNewRoute,
    AdminSitesSiteIdEntriesCollectionSlugIndexRoute:
      AdminSitesSiteIdEntriesCollectionSlugIndexRoute,
    AdminSitesSiteIdEntriesCollectionSlugIdEditRoute:
      AdminSitesSiteIdEntriesCollectionSlugIdEditRoute,
  }

const AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren =
  AdminSitesSiteIdEntriesCollectionSlugRoute._addFileChildren(
    AdminSitesSiteIdEntriesCollectionSlugRouteChildren,
  )

interface AdminSitesSiteIdRouteChildren {
  AdminSitesSiteIdCollectionsRoute: typeof AdminSitesSiteIdCollectionsRoute
  AdminSitesSiteIdFilesRoute: typeof AdminSitesSiteIdFilesRoute
  AdminSitesSiteIdSettingsRoute: typeof AdminSitesSiteIdSettingsRoute
  AdminSitesSiteIdIndexRoute: typeof AdminSitesSiteIdIndexRoute
  AdminSitesSiteIdEntriesCollectionSlugRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  AdminSitesSiteIdSingletonsSlugRoute: typeof AdminSitesSiteIdSingletonsSlugRoute
}

const AdminSitesSiteIdRouteChildren: AdminSitesSiteIdRouteChildren = {
  AdminSitesSiteIdCollectionsRoute: AdminSitesSiteIdCollectionsRoute,
  AdminSitesSiteIdFilesRoute: AdminSitesSiteIdFilesRoute,
  AdminSitesSiteIdSettingsRoute: AdminSitesSiteIdSettingsRoute,
  AdminSitesSiteIdIndexRoute: AdminSitesSiteIdIndexRoute,
  AdminSitesSiteIdEntriesCollectionSlugRoute:
    AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren,
  AdminSitesSiteIdSingletonsSlugRoute: AdminSitesSiteIdSingletonsSlugRoute,
}

const AdminSitesSiteIdRouteWithChildren =
  AdminSitesSiteIdRoute._addFileChildren(AdminSitesSiteIdRouteChildren)

interface AdminSitesRouteChildren {
  AdminSitesSiteIdRoute: typeof AdminSitesSiteIdRouteWithChildren
  AdminSitesIndexRoute: typeof AdminSitesIndexRoute
}

const AdminSitesRouteChildren: AdminSitesRouteChildren = {
  AdminSitesSiteIdRoute: AdminSitesSiteIdRouteWithChildren,
  AdminSitesIndexRoute: AdminSitesIndexRoute,
}

const AdminSitesRouteWithChildren = AdminSitesRoute._addFileChildren(
  AdminSitesRouteChildren,
)

interface AdminRouteChildren {
  AdminSitesRoute: typeof AdminSitesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSitesRoute: AdminSitesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
