/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminSitesRouteImport } from './routes/_admin/sites'
import { Route as AdminShellRouteImport } from './routes/_admin/_shell'
import { Route as AdminShellIndexRouteImport } from './routes/_admin/_shell/index'
import { Route as AdminSitesSiteIdRouteImport } from './routes/_admin/sites.$siteId'
import { Route as AdminShellSettingsRouteImport } from './routes/_admin/_shell/settings'
import { Route as AdminShellAccountRouteImport } from './routes/_admin/_shell/account'
import { Route as AdminSitesSiteIdIndexRouteImport } from './routes/_admin/sites.$siteId/index'
import { Route as AdminShellSettingsIndexRouteImport } from './routes/_admin/_shell/settings/index'
import { Route as AdminSitesSiteIdSettingsRouteImport } from './routes/_admin/sites.$siteId/settings'
import { Route as AdminSitesSiteIdFilesRouteImport } from './routes/_admin/sites.$siteId/files'
import { Route as AdminSitesSiteIdDeploymentsRouteImport } from './routes/_admin/sites.$siteId/deployments'
import { Route as AdminSitesSiteIdCollectionsRouteImport } from './routes/_admin/sites.$siteId/collections'
import { Route as AdminShellSettingsUsersRouteImport } from './routes/_admin/_shell/settings/users'
import { Route as AdminShellSettingsStorageRouteImport } from './routes/_admin/_shell/settings/storage'
import { Route as AdminShellSettingsSecurityRouteImport } from './routes/_admin/_shell/settings/security'
import { Route as AdminShellSettingsBackupsRouteImport } from './routes/_admin/_shell/settings/backups'
import { Route as AdminSitesSiteIdSettingsIndexRouteImport } from './routes/_admin/sites.$siteId/settings/index'
import { Route as AdminSitesSiteIdSingletonsSlugRouteImport } from './routes/_admin/sites.$siteId/singletons.$slug'
import { Route as AdminSitesSiteIdSettingsWebhooksRouteImport } from './routes/_admin/sites.$siteId/settings/webhooks'
import { Route as AdminSitesSiteIdSettingsMembersRouteImport } from './routes/_admin/sites.$siteId/settings/members'
import { Route as AdminSitesSiteIdSettingsMcpRouteImport } from './routes/_admin/sites.$siteId/settings/mcp'
import { Route as AdminSitesSiteIdSettingsBackupsRouteImport } from './routes/_admin/sites.$siteId/settings/backups'
import { Route as AdminSitesSiteIdSettingsApiKeysRouteImport } from './routes/_admin/sites.$siteId/settings/api-keys'
import { Route as AdminSitesSiteIdEntriesCollectionSlugRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug'
import { Route as AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/index'
import { Route as AdminSitesSiteIdEntriesCollectionSlugNewRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/new'
import { Route as AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport } from './routes/_admin/sites.$siteId/entries.$collectionSlug/$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminSitesSiteIdRoute = AdminSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AdminSitesRoute,
} as any)
const AdminShellSettingsRoute = AdminShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAccountRoute = AdminShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminSitesSiteIdIndexRoute = AdminSitesSiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSitesSiteIdRoute,
} as any)
const AdminShellSettingsIndexRoute = AdminShellSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellSettingsRoute,
} as any)
const AdminSitesSiteIdSettingsRoute =
  AdminSitesSiteIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdFilesRoute = AdminSitesSiteIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminSitesSiteIdRoute,
} as any)
const AdminSitesSiteIdDeploymentsRoute =
  AdminSitesSiteIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdCollectionsRoute =
  AdminSitesSiteIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminShellSettingsUsersRoute = AdminShellSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminShellSettingsRoute,
} as any)
const AdminShellSettingsStorageRoute =
  AdminShellSettingsStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AdminShellSettingsRoute,
  } as any)
const AdminShellSettingsSecurityRoute =
  AdminShellSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AdminShellSettingsRoute,
  } as any)
const AdminShellSettingsBackupsRoute =
  AdminShellSettingsBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AdminShellSettingsRoute,
  } as any)
const AdminSitesSiteIdSettingsIndexRoute =
  AdminSitesSiteIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdSingletonsSlugRoute =
  AdminSitesSiteIdSingletonsSlugRouteImport.update({
    id: '/singletons/$slug',
    path: '/singletons/$slug',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdSettingsWebhooksRoute =
  AdminSitesSiteIdSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdSettingsMembersRoute =
  AdminSitesSiteIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdSettingsMcpRoute =
  AdminSitesSiteIdSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdSettingsBackupsRoute =
  AdminSitesSiteIdSettingsBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdSettingsApiKeysRoute =
  AdminSitesSiteIdSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AdminSitesSiteIdSettingsRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugRoute =
  AdminSitesSiteIdEntriesCollectionSlugRouteImport.update({
    id: '/entries/$collectionSlug',
    path: '/entries/$collectionSlug',
    getParentRoute: () => AdminSitesSiteIdRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugIndexRoute =
  AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugNewRoute =
  AdminSitesSiteIdEntriesCollectionSlugNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)
const AdminSitesSiteIdEntriesCollectionSlugIdEditRoute =
  AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminSitesSiteIdEntriesCollectionSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminShellIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sites': typeof AdminSitesRouteWithChildren
  '/account': typeof AdminShellAccountRoute
  '/settings': typeof AdminShellSettingsRouteWithChildren
  '/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/settings/backups': typeof AdminShellSettingsBackupsRoute
  '/settings/security': typeof AdminShellSettingsSecurityRoute
  '/settings/storage': typeof AdminShellSettingsStorageRoute
  '/settings/users': typeof AdminShellSettingsUsersRoute
  '/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/sites/$siteId/deployments': typeof AdminSitesSiteIdDeploymentsRoute
  '/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsRouteWithChildren
  '/settings/': typeof AdminShellSettingsIndexRoute
  '/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  '/sites/$siteId/settings/api-keys': typeof AdminSitesSiteIdSettingsApiKeysRoute
  '/sites/$siteId/settings/backups': typeof AdminSitesSiteIdSettingsBackupsRoute
  '/sites/$siteId/settings/mcp': typeof AdminSitesSiteIdSettingsMcpRoute
  '/sites/$siteId/settings/members': typeof AdminSitesSiteIdSettingsMembersRoute
  '/sites/$siteId/settings/webhooks': typeof AdminSitesSiteIdSettingsWebhooksRoute
  '/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/sites/$siteId/settings/': typeof AdminSitesSiteIdSettingsIndexRoute
  '/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/sites/$siteId/entries/$collectionSlug/': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AdminShellIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sites': typeof AdminSitesRouteWithChildren
  '/account': typeof AdminShellAccountRoute
  '/settings/backups': typeof AdminShellSettingsBackupsRoute
  '/settings/security': typeof AdminShellSettingsSecurityRoute
  '/settings/storage': typeof AdminShellSettingsStorageRoute
  '/settings/users': typeof AdminShellSettingsUsersRoute
  '/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/sites/$siteId/deployments': typeof AdminSitesSiteIdDeploymentsRoute
  '/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/settings': typeof AdminShellSettingsIndexRoute
  '/sites/$siteId': typeof AdminSitesSiteIdIndexRoute
  '/sites/$siteId/settings/api-keys': typeof AdminSitesSiteIdSettingsApiKeysRoute
  '/sites/$siteId/settings/backups': typeof AdminSitesSiteIdSettingsBackupsRoute
  '/sites/$siteId/settings/mcp': typeof AdminSitesSiteIdSettingsMcpRoute
  '/sites/$siteId/settings/members': typeof AdminSitesSiteIdSettingsMembersRoute
  '/sites/$siteId/settings/webhooks': typeof AdminSitesSiteIdSettingsWebhooksRoute
  '/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsIndexRoute
  '/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_admin/_shell': typeof AdminShellRouteWithChildren
  '/_admin/sites': typeof AdminSitesRouteWithChildren
  '/_admin/_shell/account': typeof AdminShellAccountRoute
  '/_admin/_shell/settings': typeof AdminShellSettingsRouteWithChildren
  '/_admin/sites/$siteId': typeof AdminSitesSiteIdRouteWithChildren
  '/_admin/_shell/': typeof AdminShellIndexRoute
  '/_admin/_shell/settings/backups': typeof AdminShellSettingsBackupsRoute
  '/_admin/_shell/settings/security': typeof AdminShellSettingsSecurityRoute
  '/_admin/_shell/settings/storage': typeof AdminShellSettingsStorageRoute
  '/_admin/_shell/settings/users': typeof AdminShellSettingsUsersRoute
  '/_admin/sites/$siteId/collections': typeof AdminSitesSiteIdCollectionsRoute
  '/_admin/sites/$siteId/deployments': typeof AdminSitesSiteIdDeploymentsRoute
  '/_admin/sites/$siteId/files': typeof AdminSitesSiteIdFilesRoute
  '/_admin/sites/$siteId/settings': typeof AdminSitesSiteIdSettingsRouteWithChildren
  '/_admin/_shell/settings/': typeof AdminShellSettingsIndexRoute
  '/_admin/sites/$siteId/': typeof AdminSitesSiteIdIndexRoute
  '/_admin/sites/$siteId/entries/$collectionSlug': typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  '/_admin/sites/$siteId/settings/api-keys': typeof AdminSitesSiteIdSettingsApiKeysRoute
  '/_admin/sites/$siteId/settings/backups': typeof AdminSitesSiteIdSettingsBackupsRoute
  '/_admin/sites/$siteId/settings/mcp': typeof AdminSitesSiteIdSettingsMcpRoute
  '/_admin/sites/$siteId/settings/members': typeof AdminSitesSiteIdSettingsMembersRoute
  '/_admin/sites/$siteId/settings/webhooks': typeof AdminSitesSiteIdSettingsWebhooksRoute
  '/_admin/sites/$siteId/singletons/$slug': typeof AdminSitesSiteIdSingletonsSlugRoute
  '/_admin/sites/$siteId/settings/': typeof AdminSitesSiteIdSettingsIndexRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/new': typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/': typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit': typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/sites'
    | '/account'
    | '/settings'
    | '/sites/$siteId'
    | '/settings/backups'
    | '/settings/security'
    | '/settings/storage'
    | '/settings/users'
    | '/sites/$siteId/collections'
    | '/sites/$siteId/deployments'
    | '/sites/$siteId/files'
    | '/sites/$siteId/settings'
    | '/settings/'
    | '/sites/$siteId/'
    | '/sites/$siteId/entries/$collectionSlug'
    | '/sites/$siteId/settings/api-keys'
    | '/sites/$siteId/settings/backups'
    | '/sites/$siteId/settings/mcp'
    | '/sites/$siteId/settings/members'
    | '/sites/$siteId/settings/webhooks'
    | '/sites/$siteId/singletons/$slug'
    | '/sites/$siteId/settings/'
    | '/sites/$siteId/entries/$collectionSlug/new'
    | '/sites/$siteId/entries/$collectionSlug/'
    | '/sites/$siteId/entries/$collectionSlug/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/sites'
    | '/account'
    | '/settings/backups'
    | '/settings/security'
    | '/settings/storage'
    | '/settings/users'
    | '/sites/$siteId/collections'
    | '/sites/$siteId/deployments'
    | '/sites/$siteId/files'
    | '/settings'
    | '/sites/$siteId'
    | '/sites/$siteId/settings/api-keys'
    | '/sites/$siteId/settings/backups'
    | '/sites/$siteId/settings/mcp'
    | '/sites/$siteId/settings/members'
    | '/sites/$siteId/settings/webhooks'
    | '/sites/$siteId/singletons/$slug'
    | '/sites/$siteId/settings'
    | '/sites/$siteId/entries/$collectionSlug/new'
    | '/sites/$siteId/entries/$collectionSlug'
    | '/sites/$siteId/entries/$collectionSlug/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/register'
    | '/_admin/_shell'
    | '/_admin/sites'
    | '/_admin/_shell/account'
    | '/_admin/_shell/settings'
    | '/_admin/sites/$siteId'
    | '/_admin/_shell/'
    | '/_admin/_shell/settings/backups'
    | '/_admin/_shell/settings/security'
    | '/_admin/_shell/settings/storage'
    | '/_admin/_shell/settings/users'
    | '/_admin/sites/$siteId/collections'
    | '/_admin/sites/$siteId/deployments'
    | '/_admin/sites/$siteId/files'
    | '/_admin/sites/$siteId/settings'
    | '/_admin/_shell/settings/'
    | '/_admin/sites/$siteId/'
    | '/_admin/sites/$siteId/entries/$collectionSlug'
    | '/_admin/sites/$siteId/settings/api-keys'
    | '/_admin/sites/$siteId/settings/backups'
    | '/_admin/sites/$siteId/settings/mcp'
    | '/_admin/sites/$siteId/settings/members'
    | '/_admin/sites/$siteId/settings/webhooks'
    | '/_admin/sites/$siteId/singletons/$slug'
    | '/_admin/sites/$siteId/settings/'
    | '/_admin/sites/$siteId/entries/$collectionSlug/new'
    | '/_admin/sites/$siteId/entries/$collectionSlug/'
    | '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/sites': {
      id: '/_admin/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/_shell': {
      id: '/_admin/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/_shell/': {
      id: '/_admin/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_admin/sites/$siteId': {
      id: '/_admin/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AdminSitesSiteIdRouteImport
      parentRoute: typeof AdminSitesRoute
    }
    '/_admin/_shell/settings': {
      id: '/_admin/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminShellSettingsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_admin/_shell/account': {
      id: '/_admin/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AdminShellAccountRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_admin/sites/$siteId/': {
      id: '/_admin/sites/$siteId/'
      path: '/'
      fullPath: '/sites/$siteId/'
      preLoaderRoute: typeof AdminSitesSiteIdIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/_shell/settings/': {
      id: '/_admin/_shell/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminShellSettingsIndexRouteImport
      parentRoute: typeof AdminShellSettingsRoute
    }
    '/_admin/sites/$siteId/settings': {
      id: '/_admin/sites/$siteId/settings'
      path: '/settings'
      fullPath: '/sites/$siteId/settings'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/files': {
      id: '/_admin/sites/$siteId/files'
      path: '/files'
      fullPath: '/sites/$siteId/files'
      preLoaderRoute: typeof AdminSitesSiteIdFilesRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/deployments': {
      id: '/_admin/sites/$siteId/deployments'
      path: '/deployments'
      fullPath: '/sites/$siteId/deployments'
      preLoaderRoute: typeof AdminSitesSiteIdDeploymentsRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/collections': {
      id: '/_admin/sites/$siteId/collections'
      path: '/collections'
      fullPath: '/sites/$siteId/collections'
      preLoaderRoute: typeof AdminSitesSiteIdCollectionsRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/_shell/settings/users': {
      id: '/_admin/_shell/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AdminShellSettingsUsersRouteImport
      parentRoute: typeof AdminShellSettingsRoute
    }
    '/_admin/_shell/settings/storage': {
      id: '/_admin/_shell/settings/storage'
      path: '/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof AdminShellSettingsStorageRouteImport
      parentRoute: typeof AdminShellSettingsRoute
    }
    '/_admin/_shell/settings/security': {
      id: '/_admin/_shell/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AdminShellSettingsSecurityRouteImport
      parentRoute: typeof AdminShellSettingsRoute
    }
    '/_admin/_shell/settings/backups': {
      id: '/_admin/_shell/settings/backups'
      path: '/backups'
      fullPath: '/settings/backups'
      preLoaderRoute: typeof AdminShellSettingsBackupsRouteImport
      parentRoute: typeof AdminShellSettingsRoute
    }
    '/_admin/sites/$siteId/settings/': {
      id: '/_admin/sites/$siteId/settings/'
      path: '/'
      fullPath: '/sites/$siteId/settings/'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/singletons/$slug': {
      id: '/_admin/sites/$siteId/singletons/$slug'
      path: '/singletons/$slug'
      fullPath: '/sites/$siteId/singletons/$slug'
      preLoaderRoute: typeof AdminSitesSiteIdSingletonsSlugRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/settings/webhooks': {
      id: '/_admin/sites/$siteId/settings/webhooks'
      path: '/webhooks'
      fullPath: '/sites/$siteId/settings/webhooks'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsWebhooksRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/settings/members': {
      id: '/_admin/sites/$siteId/settings/members'
      path: '/members'
      fullPath: '/sites/$siteId/settings/members'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsMembersRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/settings/mcp': {
      id: '/_admin/sites/$siteId/settings/mcp'
      path: '/mcp'
      fullPath: '/sites/$siteId/settings/mcp'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsMcpRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/settings/backups': {
      id: '/_admin/sites/$siteId/settings/backups'
      path: '/backups'
      fullPath: '/sites/$siteId/settings/backups'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsBackupsRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/settings/api-keys': {
      id: '/_admin/sites/$siteId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/sites/$siteId/settings/api-keys'
      preLoaderRoute: typeof AdminSitesSiteIdSettingsApiKeysRouteImport
      parentRoute: typeof AdminSitesSiteIdSettingsRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug'
      path: '/entries/$collectionSlug'
      fullPath: '/sites/$siteId/entries/$collectionSlug'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRouteImport
      parentRoute: typeof AdminSitesSiteIdRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/'
      path: '/'
      fullPath: '/sites/$siteId/entries/$collectionSlug/'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIndexRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/new': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/new'
      path: '/new'
      fullPath: '/sites/$siteId/entries/$collectionSlug/new'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugNewRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
    '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit': {
      id: '/_admin/sites/$siteId/entries/$collectionSlug/$id/edit'
      path: '/$id/edit'
      fullPath: '/sites/$siteId/entries/$collectionSlug/$id/edit'
      preLoaderRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRouteImport
      parentRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRoute
    }
  }
}

interface AdminShellSettingsRouteChildren {
  AdminShellSettingsBackupsRoute: typeof AdminShellSettingsBackupsRoute
  AdminShellSettingsSecurityRoute: typeof AdminShellSettingsSecurityRoute
  AdminShellSettingsStorageRoute: typeof AdminShellSettingsStorageRoute
  AdminShellSettingsUsersRoute: typeof AdminShellSettingsUsersRoute
  AdminShellSettingsIndexRoute: typeof AdminShellSettingsIndexRoute
}

const AdminShellSettingsRouteChildren: AdminShellSettingsRouteChildren = {
  AdminShellSettingsBackupsRoute: AdminShellSettingsBackupsRoute,
  AdminShellSettingsSecurityRoute: AdminShellSettingsSecurityRoute,
  AdminShellSettingsStorageRoute: AdminShellSettingsStorageRoute,
  AdminShellSettingsUsersRoute: AdminShellSettingsUsersRoute,
  AdminShellSettingsIndexRoute: AdminShellSettingsIndexRoute,
}

const AdminShellSettingsRouteWithChildren =
  AdminShellSettingsRoute._addFileChildren(AdminShellSettingsRouteChildren)

interface AdminShellRouteChildren {
  AdminShellAccountRoute: typeof AdminShellAccountRoute
  AdminShellSettingsRoute: typeof AdminShellSettingsRouteWithChildren
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAccountRoute: AdminShellAccountRoute,
  AdminShellSettingsRoute: AdminShellSettingsRouteWithChildren,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface AdminSitesSiteIdSettingsRouteChildren {
  AdminSitesSiteIdSettingsApiKeysRoute: typeof AdminSitesSiteIdSettingsApiKeysRoute
  AdminSitesSiteIdSettingsBackupsRoute: typeof AdminSitesSiteIdSettingsBackupsRoute
  AdminSitesSiteIdSettingsMcpRoute: typeof AdminSitesSiteIdSettingsMcpRoute
  AdminSitesSiteIdSettingsMembersRoute: typeof AdminSitesSiteIdSettingsMembersRoute
  AdminSitesSiteIdSettingsWebhooksRoute: typeof AdminSitesSiteIdSettingsWebhooksRoute
  AdminSitesSiteIdSettingsIndexRoute: typeof AdminSitesSiteIdSettingsIndexRoute
}

const AdminSitesSiteIdSettingsRouteChildren: AdminSitesSiteIdSettingsRouteChildren =
  {
    AdminSitesSiteIdSettingsApiKeysRoute: AdminSitesSiteIdSettingsApiKeysRoute,
    AdminSitesSiteIdSettingsBackupsRoute: AdminSitesSiteIdSettingsBackupsRoute,
    AdminSitesSiteIdSettingsMcpRoute: AdminSitesSiteIdSettingsMcpRoute,
    AdminSitesSiteIdSettingsMembersRoute: AdminSitesSiteIdSettingsMembersRoute,
    AdminSitesSiteIdSettingsWebhooksRoute:
      AdminSitesSiteIdSettingsWebhooksRoute,
    AdminSitesSiteIdSettingsIndexRoute: AdminSitesSiteIdSettingsIndexRoute,
  }

const AdminSitesSiteIdSettingsRouteWithChildren =
  AdminSitesSiteIdSettingsRoute._addFileChildren(
    AdminSitesSiteIdSettingsRouteChildren,
  )

interface AdminSitesSiteIdEntriesCollectionSlugRouteChildren {
  AdminSitesSiteIdEntriesCollectionSlugNewRoute: typeof AdminSitesSiteIdEntriesCollectionSlugNewRoute
  AdminSitesSiteIdEntriesCollectionSlugIndexRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIndexRoute
  AdminSitesSiteIdEntriesCollectionSlugIdEditRoute: typeof AdminSitesSiteIdEntriesCollectionSlugIdEditRoute
}

const AdminSitesSiteIdEntriesCollectionSlugRouteChildren: AdminSitesSiteIdEntriesCollectionSlugRouteChildren =
  {
    AdminSitesSiteIdEntriesCollectionSlugNewRoute:
      AdminSitesSiteIdEntriesCollectionSlugNewRoute,
    AdminSitesSiteIdEntriesCollectionSlugIndexRoute:
      AdminSitesSiteIdEntriesCollectionSlugIndexRoute,
    AdminSitesSiteIdEntriesCollectionSlugIdEditRoute:
      AdminSitesSiteIdEntriesCollectionSlugIdEditRoute,
  }

const AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren =
  AdminSitesSiteIdEntriesCollectionSlugRoute._addFileChildren(
    AdminSitesSiteIdEntriesCollectionSlugRouteChildren,
  )

interface AdminSitesSiteIdRouteChildren {
  AdminSitesSiteIdCollectionsRoute: typeof AdminSitesSiteIdCollectionsRoute
  AdminSitesSiteIdDeploymentsRoute: typeof AdminSitesSiteIdDeploymentsRoute
  AdminSitesSiteIdFilesRoute: typeof AdminSitesSiteIdFilesRoute
  AdminSitesSiteIdSettingsRoute: typeof AdminSitesSiteIdSettingsRouteWithChildren
  AdminSitesSiteIdIndexRoute: typeof AdminSitesSiteIdIndexRoute
  AdminSitesSiteIdEntriesCollectionSlugRoute: typeof AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren
  AdminSitesSiteIdSingletonsSlugRoute: typeof AdminSitesSiteIdSingletonsSlugRoute
}

const AdminSitesSiteIdRouteChildren: AdminSitesSiteIdRouteChildren = {
  AdminSitesSiteIdCollectionsRoute: AdminSitesSiteIdCollectionsRoute,
  AdminSitesSiteIdDeploymentsRoute: AdminSitesSiteIdDeploymentsRoute,
  AdminSitesSiteIdFilesRoute: AdminSitesSiteIdFilesRoute,
  AdminSitesSiteIdSettingsRoute: AdminSitesSiteIdSettingsRouteWithChildren,
  AdminSitesSiteIdIndexRoute: AdminSitesSiteIdIndexRoute,
  AdminSitesSiteIdEntriesCollectionSlugRoute:
    AdminSitesSiteIdEntriesCollectionSlugRouteWithChildren,
  AdminSitesSiteIdSingletonsSlugRoute: AdminSitesSiteIdSingletonsSlugRoute,
}

const AdminSitesSiteIdRouteWithChildren =
  AdminSitesSiteIdRoute._addFileChildren(AdminSitesSiteIdRouteChildren)

interface AdminSitesRouteChildren {
  AdminSitesSiteIdRoute: typeof AdminSitesSiteIdRouteWithChildren
}

const AdminSitesRouteChildren: AdminSitesRouteChildren = {
  AdminSitesSiteIdRoute: AdminSitesSiteIdRouteWithChildren,
}

const AdminSitesRouteWithChildren = AdminSitesRoute._addFileChildren(
  AdminSitesRouteChildren,
)

interface AdminRouteChildren {
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminSitesRoute: typeof AdminSitesRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminSitesRoute: AdminSitesRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
